# Generated by Django 3.2 on 2023-06-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='count',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
