# Generated by Django 3.2 on 2023-06-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.user'),
            preserve_default=False,
        ),
    ]
