# Generated by Django 3.2 on 2023-06-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230606_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
