# Generated by Django 3.2 on 2023-06-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
