# Generated by Django 3.2 on 2023-06-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_user_username'),
        ('reviews', '0010_alter_review_title'),
    ]

    operations = [
    ]
